apiVersion: apps/v1
kind: Deployment
metadata:
  name: flash-book-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flash-book-api
  template:
    metadata:
      labels:
        app: flash-book-api
    spec:
      containers:
        - name: flash-book-api
          image: abhishekcrm/flash-book-api:latest  # Ensure this image name is correct
          ports:
<<<<<<< HEAD
            - containerPort: 5000
=======
            - containerPort: 5000
>>>>>>> 6083ecb13b8530711c343fb52b92ecb52d98c68b
