apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-api
  template:
    metadata:
      labels:
        app: crud-api
    spec:
      containers:
      - name: crud-api
        image: <your-dockerhub-username>/crud-api:latest
        ports:
        - containerPort: 5000
